### ISSUE TITLE
mocktail 0.3.0-dev.1 and freezed 1.1.1: version solving failed

### ISSUE THREAD

**Issue by ljonya** [felangel/mocktail#105]
**Describe the bug**
I am trying to use freezed and mocktail in the same project, but mocktail won't install

**To Reproduce**
Dependencies in my pubspec.yaml:
```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.3
  mocktail: ^0.3.0-dev.1
  flutter_lints: ^1.0.4
```

**Logs**
```sh
$ flutter pub get
Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.0-nullsafety.19 <1.17.10 requires test_api 0.2.19 or analyzer ^1.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0 and test >=1.20.0 depends on test_api 0.4.9, test >=1.16.0-nullsafety.19 requires test_api 0.2.19 or 0.4.9 or analyzer >=1.0.0 <3.0.0.
Because no versions of freezed match >1.1.1 <2.0.0 and freezed 1.1.1 depends on analyzer ^3.0.0, freezed ^1.1.1 requires analyzer ^3.0.0.
Thus, if freezed ^1.1.1 and test >=1.16.0-nullsafety.19 then test_api 0.2.19 or 0.4.9.
And because mocktail >=0.1.0 depends on test ^1.16.0, if freezed ^1.1.1 and mocktail >=0.1.0 then test_api 0.2.19 or 0.4.9.
And because msc depends on flutter_test from sdk which depends on test_api 0.4.3, freezed ^1.1.1 is incompatible with mocktail >=0.1.0.
So, because msc depends on both freezed ^1.1.1 and mocktail ^0.3.0-dev.1, version solving failed.
Running "flutter pub get" in msc...                                     
pub get failed (1; So, because msc depends on both freezed ^1.1.1 and mocktail ^0.3.0-dev.1, version solving failed.)
```

**Comment by felangel** [comment]
Hi @ljonya 👋
Thanks for opening an issue!

I believe this is a duplicate of https://github.com/felangel/bloc/issues/3110#issuecomment-1004381832. Let me know if that helps 👍

**Comment by ljonya** [comment]
@felangel Hi! Thank you so much! Indeed, this is the same problem.

**Comment by foxanna** [comment]
Hi @felangel,
I guess if it was only about `freezed` and `flutter_test`, running `flutter pub get` on such `pubspec.yaml` would also fail:
```yaml
environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.1'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
#  mocktail: ^0.3.0-dev.1
```

But it does not. It only fails if `mocktail` dependency (both `0.2.0` or `0.3.0-dev.1`) is uncommented.
