### ISSUE TITLE
Bump test dependency to last release

### ISSUE THREAD

**Issue by MarcoAFC** [felangel/mocktail#152]
**Is your feature request related to a problem? Please describe.**
Current build depends on an older version of test, which creates a transitive dependency on analyzer < 5, making it incompatible with later releases of packages that depend on analyzer >= 5 (such as the latest release of freezed)

```
[app] flutter pub get Running "flutter pub get" in app...
And because mocktail 0.3.0 depends on test ^1.16.0 and no versions of mocktail match >0.3.0 <0.4.0, if flutter_test from sdk and mocktail ^0.3.0 then analyzer >=1.0.0 <5.0.0.
And because app depends on freezed ^2.1.1 which depends on analyzer ^5.0.0, flutter_test from sdk is incompatible with mocktail ^0.3.0.
So, because app depends on both mocktail ^0.3.0 and flutter_test from sdk, version solving failed.
```

**Describe the solution you'd like**
I'd like a new release, compatible with later releases of test library.

**Describe alternatives you've considered**
Bump restrictions on min dart sdk and increase dependency version

**Comment by felangel** [comment]
Hi @MarcoAFC 👋
Can you please provide a sample `pubspec.yaml` that illustrates the issue?

It seems a bit strange to me because mocktail doesn’t require a strict version of package:test and the version range is permissive of the latest version. Thanks!

**Comment by MarcoAFC** [comment]
Hi!

It seems the error actually only appears when using both freezed and bloc,

So, this is enough to break:

```
name: testing
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed: ^2.1.1
  mocktail: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

**Comment by felangel** [comment]
@MarcoAFC I took a closer look and it looks like freezed requires `analyzer ^5.0.0` which is incompatible with the latest stable version of `flutter_test` and `package:test`:

```yaml
name: example
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.0
  freezed: ^2.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
