### ISSUE TITLE
`verify` function rest verified calls

### ISSUE THREAD

**Issue by yehorh** [felangel/mocktail#176]
**Describe the bug**
`verify` function rest verified calls

**To Reproduce**

> example from README.md
```dart
// A Real Cat class
class Cat {
  String sound() => 'meow!';

  bool likes(String food, {bool isHungry = false}) => false;
  final int lives = 9;
}

// A Mock Cat class
class MockCat extends Mock implements Cat {}

void main() {
  test('README example', () {
    // Create a Mock Cat instance
    final cat = MockCat();
    // Stub the `sound` method.
    when(() => cat.sound()).thenReturn('meow');

    // Verify no interactions have occurred.
    verifyNever(() => cat.sound());

    // Interact with the mock cat instance.
    cat.sound();

    // Verify the interaction occurred.
    verify(() => cat.sound()).called(1);

    // Interact with the mock instance again.
    cat.sound();

    // Verify the interaction occurred twice.
    verify(() => cat.sound()).called(2);
  });
}
```

```
Expected: <2>
  Actual: <1>
Unexpected number of calls
```

**Additional context**
```
mocktail:
    dependency: "direct dev"
    description:
      name: mocktail
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.0"
```
